### ISSUE TITLE
Compilation error: 'ledcSetup' was not declared in this scope

### ISSUE THREAD

**Issue by steveo212** [VolosR/VolumeKnob#1]
Possibly newb issue here but I downloaded, compiled and got the following error:

/Users/steve/projects/Arduino/VolumeKnob-main/VolumeKnob/VolumeKnob.ino: In function 'void setup()':
/Users/steve/projects/Arduino/VolumeKnob-main/VolumeKnob/VolumeKnob.ino:65:6: error: 'ledcSetup' was not declared in this scope
   65 |      ledcSetup(0, 10000, 8);
      |      ^~~~~~~~~
/Users/steve/projects/Arduino/VolumeKnob-main/VolumeKnob/VolumeKnob.ino:66:6: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
   66 |      ledcAttachPin(TFT_BLK, 0);
      |      ^~~~~~~~~~~~~
      |      ledcAttach

If I comment out line 65 and add another parameter to line 66 it compiles but I can't seem to get it to work after upload. Attached is the compiler output. 
FYI, I did follow the instructions on https://wiki.makerfabs.com/MaTouch_ESP32_S3_Rotary_IPS_Display_1.28_GC9A01.html#usage and was successful.  
 
[VolumeKnob_Compile_Error.txt](https://github.com/user-attachments/files/15962670/VolumeKnob_Compile_Error.txt)

**Comment by steveo212** [comment]
Compiles correctly using version 2.0.10!!! wow it's working! I know it was a newb question but hopefully this helps someone.
